### ISSUE TITLE
[QUESTION] How to respond with a 404?

### ISSUE THREAD

**Issue by dotnetCarpenter** [fluture-js/fluture-express#36]
I can't find an example of how to implement a redirect that rejects with a HTTP 404 code.

EDIT: My goal is to create a re-write action to handle when resources, for what-ever reason, gets renamed. As such, I guess the correct way to handle that, is to always use `Next (locals)`. But the question remains, what is the idiomatic way to respond with HTTP error code? DO you always `resolve`? If yes, is all `reject` a server error? And what is the correct way to use `withStatus`? `withStatus (404) (Body.None)` gives `TypeError: Constructors given to cata didn't include: None`

While the following works, it's not exactly what I had in mine.
```js
import { Redirect } from "fluture-express"
import { resolve, reject } from "fluture"

export default _ => request => {
  return request.path === "test1"
    ? resolve (Redirect ("/"))
    : reject ("Not found")
}
```

I tried to use the `withStatus` function but unsure how I'm suppose to use it. And the following doesn't do what I want either.
```js
import { Redirect, withStatus } from "fluture-express"
import { resolve, reject } from "fluture"

export default _ => request => {
  return request.path === "test1"
    ? resolve (Redirect ("/"))
    : reject (withStatus (404))
}
```

The implementation of `Redirect` says the first argument is the HTTP status code but the first argument is `location`?
```js
//# Redirect :: String -> Response a b
//.
//. Indicates a redirection. The first argument will be the response status
//. code, and the second will be the value of the Location header.
//.
//. Unless overridden by [`withStatus`](#withStatus), the status code will be
//. set to 301 (Moved Permanently).
export const Redirect = location => Response.Respond (
  [Head.Status (301), Head.Location (location)],
  Body.None
);
```

Should I use `Response.Respond`? It's feels like I'm doing something that "fluture-express" already got a function for..

```js
import { Redirect, Response, Head, Body } from "fluture-express"
import { resolve, reject } from "fluture"

export default _ => request => {
  return request.path === "test1"
    ? resolve (Redirect ("/"))
    : resolve (Response.Respond ([Head.Status (404)], Body.None))
}
```

**Comment by Avaq** [comment]
> The implementation of Redirect says the first argument is the HTTP status code but the first argument is location?

Oh! This is a mistake in the documentation — a leftover from an older version. The second sentence is correct: It only takes the location, and sets the status to 301. If you want to override the status, you need to compose with `withStatus` like so:

```js
const res = pipe ([
  Redirect ("https://example.com"),
  withStatus (304)
])
```

**Comment by Avaq** [comment]
> But the question remains, what is the idiomatic way to respond with HTTP error code? DO you always resolve? If yes, is all reject a server error?

That's how I'd build my apps, yes. The Future always resolves with a Response, or rejects with an error. That error is then handled by the [Express error handling mechanism](https://expressjs.com/en/guide/error-handling.html)

**Comment by Avaq** [comment]
> And what is the correct way to use `withStatus`? `withStatus (404) (Body.None)` gives `TypeError: Constructors given to cata didn't include: None`

That's because the types don't align. Look at the type of `withStatus`:

```hs
withStatus :: Number -⁠> Response a b -⁠> Response a b
```

It takes a number, and then turns a Response into another Response. What about `Body.None`?

```hs
Body.None :: Body a
```

That's a Body, not a Response. `withStatus` takes a Response, not a Body.

To create a Response with an empty body, you can do:

```js
Response.Respond ([], Body.None)
```

This wraps the response _body_ (which is only part of the response) in a full Response, which is what `withStatus` expects.

But you don't need to use the data constructors like that directly. You can do everything with the documented functions. For example, the empty response we made above is the same as the `Empty` export. So an empty response with 404 can be made like this:

```js
pipe ([Empty, withStatus (404)])
```

**Comment by Avaq** [comment]
(oh, I didn't really remember the `pipe` function; I think it could be `pipe (Empty) ([withStatus (404)])` and such)

**Comment by dotnetCarpenter** [comment]
> (oh, I didn't really remember the `pipe` function; I think it could be `pipe (Empty) ([withStatus (404)])` and such)

I’m away from pc but I as I recall, you’re thinking of `S.compose`…

Thanks for a delightful answer, as always 😄
